### ISSUE TITLE
Aba Financeiro

### ISSUE THREAD

**Issue by leanog** [leonardovilarinho/prontuario-sus#1]
Para usuários Médicos E Profissionais: 
Implementação da aba "Financeiro" para controle financeiro. Interessante implementar uma opção de editar valores pois durante o atendimento o médico pode conceder desconto ou cobrança extra por novo procedimento durante a consulta.

Como sugestão desenhei o modelo em anexo.
![financeito](https://user-images.githubusercontent.com/30274924/29147732-42e6883a-7d3f-11e7-9bf7-a2ffe164704c.jpg)

após implementação dessa aba pode-se excluir o botão "Mostrar/ocultar preços das consultas"

**Comment by leonardovilarinho** [comment]
Foi corrigido no commit fc23593d19f52facb592867d2510eb5aed27f1d9
Baixe a nova versão em https://github.com/leonardovilarinho/prontuario-sus/releases/tag/v1.2 e siga as instruções para atualizar.
