### ISSUE TITLE
Permitir o cadastro de mais de um número de telefone

### ISSUE THREAD

**Issue by leanog** [leonardovilarinho/prontuario-sus#10]
Atualmente ao cadastrar um paciente o sistema está com a quantidade de caracteres limitados a inserção de apenas um número de telefone.

Se torna interessante a liberação da quantidade de caracteres para um número maior ou então a criação de campos extras para mais números de telefone

**Comment by leanog** [comment]
Baixa prioridade

**Comment by leonardovilarinho** [comment]
Agora o campo de telefone aceita mais números, possibilitando acrescentar mais telefones
