### ISSUE TITLE
Mais informações a um clique

### ISSUE THREAD

**Issue by leanog** [leonardovilarinho/prontuario-sus#13]
Para facilitar o atendimento e agilizar a leitura das informações, se torna interessante a criação de um botão para ver todo o histórico de evoluções (e receitas?) do histórico do paciente com apenas um clique.

Seria um botão como sugerido na imagem abaixo que ao ser pressionado abriria uma nova tela (pop-up ?) com a listagem de todas informações reunidas em uma única tela em ordem cronológica.

![melhorias pep 5](https://user-images.githubusercontent.com/30274924/30866875-d347f846-a2b0-11e7-8d2b-7cd0547cdb30.jpg)

Exemplo da tela que seria aberta após clicar no botão:

_"01/09/2017 - Dr Fulano 
paciente com tosse e dor no pulmão
*
03/09/2017- Dr Beltrano
Paciente retorna com RX de pulmão, mantem tosse
prescrevo um antibiótico
*
15/09/2017 --- Dr Fulano
melhora das queixas.
Conduta: alta médica"_

**Comment by leanog** [comment]
Baixa prioridade

**Comment by leonardovilarinho** [comment]
Implementado, segue a tela de histórico de evoluções:

![deepin screenshot_selecionar area_20180210171213](https://user-images.githubusercontent.com/12480135/36065703-a213b594-0e85-11e8-8dd2-1538c6aedafe.png)


PS: também é possível ver histórico de receituários.
