### ISSUE TITLE
Mais privacidade para Médicos e Profissionais

### ISSUE THREAD

**Issue by leanog** [leonardovilarinho/prontuario-sus#14]
Alguns Médicos e Profissionais estão com uma demanda de possuir também um login como secretário para que eles mesmos possam agendar consultas e retornos diretamente de dentro de seus consultórios.

Problema de privacidade: ao dar essa opção seria possível ter acesso a agenda dos demais Profissionais e Médicos (inclusive olhar valor financeiro de consultas já marcadas)

Uma boa solução seria se o administrador puder cadastrar quais os Secretários podem agendar Consulta nas agendas desses profissionais, com uma solução semelhante a usada no cadastro de posto atrelados aos médicos.

Uma sugestão seria como na ilustração a seguir:
![melhorias pep7](https://user-images.githubusercontent.com/30274924/30993000-0fe5e2ee-a483-11e7-892a-25a086b09881.jpg)

.
.
Ao clicar em "Secretários" iria abrir uma tela semelhante a da escolha dos postos, como ilustrado a baixo:
![melhorias pep8](https://user-images.githubusercontent.com/30274924/30993210-347e1e86-a484-11e7-994f-b761eba437c1.jpg)

Outra melhoria que ocorreria simultaneamente com essa atualização seria o secretário, ao marcar uma consulta, terá a tela menos poluída pois só poderá agendar as consultas (e portanto só terá impresso na tela) os médicos que lhe são autorizados

**Comment by leonardovilarinho** [comment]
Foi implementado, segue a tela de seleção de secretários:

![deepin screenshot_selecionar area_20180210174400](https://user-images.githubusercontent.com/12480135/36066123-8d5ac498-0e8b-11e8-8f92-98e7ec7afa49.png)


O secretário só poderá gerenciar os médicos e profissionais vinculados a ele.
