### ISSUE TITLE
Mais agilidade para marcação de consultas

### ISSUE THREAD

**Issue by leanog** [leonardovilarinho/prontuario-sus#21]
**Usuário: Secretária**

Na forma atual de marcação de consulta a secretária precisa primeiro clicar em "médicos", selecionar o médico e em seguida clicar em "marcar consulta"; sendo que para isso antes é necessário cadastrar o paciente.

Talvez seja possível criar também a forma diferente de marcação. Para o paciente já cadastrado criar um botão "marcar consulta", após clicar selecionar o médico e então a data.

<br> <br>

_Exemplo:_

![pep4](https://user-images.githubusercontent.com/30274924/98719118-1a53b400-236e-11eb-9fbc-66b543efee30.png)

**Comment by leonardovilarinho** [comment]
Feito
