### ISSUE TITLE
Melhorar a remarcação de consultas

### ISSUE THREAD

**Issue by leanog** [leonardovilarinho/prontuario-sus#22]
**Usuario: Secretária**

Atualmente quando um paciente liga para remarcar uma consulta é necessário desmarcar e marcar novamente, perde-se muito tempo ao telefone.

Talvez seja possível habilitar a edição de data da consulta diretamente dentro do perfil do paciente. Atualmente é possível trocar apenas o valor e o Status da consulta.
<br>

_Exemplo:_

![pep5](https://user-images.githubusercontent.com/30274924/98719656-ca292180-236e-11eb-8b6d-6dc3faadfe80.jpg)

**Comment by leonardovilarinho** [comment]
Feito
