### ISSUE TITLE
Mais velocidade na filtragem da agenda

### ISSUE THREAD

**Issue by leanog** [leonardovilarinho/prontuario-sus#23]
**Usuario: secretária**

No login da secretária ao clicar "médicos" --> selecionar um médico --> clicar em "Consultas", abre uma agenda bem desorganizada.
Criar um botão "Consultas de Hoje" vai ajudar na velocidade da filtragem das consultas que estão ocorrendo; se tiver espaço também pode criar um botão "consultas de amanhã" e um outro "consultas de ontem".

_Exemplo:_

![pep6](https://user-images.githubusercontent.com/30274924/98722181-cd70dd00-236f-11eb-8bdf-aae898f2b896.jpg)

**Comment by leonardovilarinho** [comment]
Adicionei os botões de consulta, o mudar a data está em outra tarefa, que é algo mais complexo pois tem todas validações a fazer
