### ISSUE TITLE
Limpeza de tela 2 + melhorias

### ISSUE THREAD

**Issue by leanog** [leonardovilarinho/prontuario-sus#26]
**Usuário: Secretária**

- Na guia Médicos suprimir os dados das colunas Email, Conselho e Nascimento; acrescentar o botão que permite cadastrar novos médicos da mesma forma que já está diponível para cadastrar novas secretárias e novos profissionais e trazer para esta tela o link do botão "Consultas" que está dentro do botão "gerenciar"

Exemplo:

![PEPn02](https://user-images.githubusercontent.com/30274924/99012370-fe4a4100-252c-11eb-9fcf-dcdc479dd644.jpg)
<br><br>

- Na guia Profissionais mesma alteração, porém já possu o botão "cadastrar novo profissional"

_Exemplo:_
![PEPn03](https://user-images.githubusercontent.com/30274924/99012478-3e112880-252d-11eb-9c79-140bdde1d838.jpg)

- Na guia Secretarias apenas suprimir as informações Email e CPF
_Exemplo:_
![PEPn04](https://user-images.githubusercontent.com/30274924/99012517-5bde8d80-252d-11eb-8bc3-0b7fb689ab6f.jpg)

**Comment by leonardovilarinho** [comment]
Feito, também corrigi bugs que vi na paginação de Profissionais e Médicos na visão do secretário
