### ISSUE TITLE
Nova tela inicial para as Secretárias

### ISSUE THREAD

**Issue by leanog** [leonardovilarinho/prontuario-sus#27]
**Usuário: Secretária**

Após login no sistema abrir uma página com todas as consultas agendadas por horário e médico/profissional para o corrente dia vai ajudar na organização do fluxo das clínicas
_Exemplo:_

![pepn05](https://user-images.githubusercontent.com/30274924/99012680-afe97200-252d-11eb-918e-c0d68d4cc408.jpg)

**Comment by leonardovilarinho** [comment]
Feito
