### ISSUE TITLE
Correção de bug na pesquisa por data de consulta

### ISSUE THREAD

**Issue by leanog** [leonardovilarinho/prontuario-sus#3]
No usuário secretário:

Ao clicar em "médicos" --> "Gerenciar" --> "consultas"  a opção de buscar por data da consulta não está funcionando corretamente. 
Como extra poderia tambem adicionar um botão "imprimir"

![busca](https://user-images.githubusercontent.com/30274924/29148431-ac6e9b7c-7d43-11e7-8ebd-8d8ce096dbad.jpg)

**Comment by leonardovilarinho** [comment]
Foi corrigido no commit fc23593d19f52facb592867d2510eb5aed27f1d9
Baixe a nova versão em https://github.com/leonardovilarinho/prontuario-sus/releases/tag/v1.2 e siga as instruções para atualizar.
