### ISSUE TITLE
Correção de Bug

### ISSUE THREAD

**Issue by leanog** [leonardovilarinho/prontuario-sus#4]
Após o usuário Médico (ou Profissional) clicar no botão "Finalizar" as consultas finalizadas ou aguardando atendimento não são atualizadas na tela da secretária (para a secretária ver a agenda: "medicos"--> "gerenciar"--> "consultas"

![finalizar](https://user-images.githubusercontent.com/30274924/29148855-72a80c68-7d46-11e7-8346-f41525d6c95a.jpg)
![finalizar2](https://user-images.githubusercontent.com/30274924/29148854-72a79e18-7d46-11e7-949a-3ef0cf2c4b37.jpg)
![finalizar3](https://user-images.githubusercontent.com/30274924/29148856-72ab8ef6-7d46-11e7-9ed7-2e4b3cdce98f.jpg)

Na tela do secretário o status muda de "pendente" para "concluída" apenas após ultrapassar o horário previamente agendado para a consulta (independende da ação do médico ter clicado ou não em finalizado)

**Comment by leonardovilarinho** [comment]
Foi corrigido no commit fc23593d19f52facb592867d2510eb5aed27f1d9
Baixe a nova versão em https://github.com/leonardovilarinho/prontuario-sus/releases/tag/v1.2 e siga as instruções para atualizar.
