### ISSUE TITLE
Bug grave ao apagar posto

### ISSUE THREAD

**Issue by leanog** [leonardovilarinho/prontuario-sus#5]
Quando um administrador apaga um posto todas as evoluções médicas (que usaram este posto apagado no cabeçalho) são apagadas juntas.

Para uma solução rápida uma sugestão seria trocar o botão "excluir" por "bloquear", assim o posto deixaria de aparecer como uma opção para os médicos.

Uma correção mais completa poderia envolver também uma lista onde cada médico pudesse ser atrelado a um ou mais postos específicos pelo administrador, nesse tipo de solução poderiam haver dezenas de postos e o médico iria ver em sua lista apenas os postos que ele está habilitado a trabalhar

**Comment by leonardovilarinho** [comment]
Foi trocada pela opção de ativar de desativar no commit fc23593d19f52facb592867d2510eb5aed27f1d9
Baixe a nova versão em https://github.com/leonardovilarinho/prontuario-sus/releases/tag/v1.2 e siga as instruções para atualizar.
