### ISSUE TITLE
Bug posto não selecionado

### ISSUE THREAD

**Issue by leanog** [leonardovilarinho/prontuario-sus#6]
Caso um usuario médico não selecione um posto (em seu primeiro acesso ao sistema) o mesmo ao cadastrar um documento (evolução ou receituario) a mesma não salva e tambem não apresenta mensagem de erro dizendo que não foi salva pois não havia nenhum posto de trabalho selecionado

**Comment by leonardovilarinho** [comment]
Não é bug, é impossível ter uma documentação sem o posto. Quando o médico tenta criar um documento sem antes ter se inserido em um posto é exibida a mensagem "Você não está e um posto"
